a = int(input("Enter the first number : "))
b = int(input("Enter the second number : "))
print("Before swapping : ")
print("a : {} b : {}".format(a, b))
(a, b) = (b, a)
print("After swapping : ")
print("a : {} b : {}".format(a, b))
